apiVersion: v2
name: bankapp
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

# The name of the chart's dependencies. Dependencies are other charts that this chart depends on.
# They are typically other applications or libraries that this chart needs to function correctly.
# Dependencies are defined in the `dependencies` section below.
# Each dependency should specify its name, version, and repository.
# Dependencies can be used to include other charts in your chart, allowing you to compose complex applications
# from smaller, reusable components.
# The dependencies are fetched from the specified repositories and can be used in your templates.
dependencies:
  - name: mysql
    version: "13.0.2"
    repository: "https://charts.bitnami.com/bitnami"

